--DROP SEQUENCE IF EXISTS EMP_ID_SEQ;
--DROP SEQUENCE IF EXISTS ROLES_ID_SEQ;
--DROP SEQUENCE IF EXISTS DEPTS_ID_SEQ;
--
--DROP TABLE IF EXISTS Employees;
--DROP TABLE IF EXISTS Roles;
--DROP TABLE IF EXISTS Departments;

--delete from flyway_schema_history;

DROP SEQUENCE  EMP_ID_SEQ;
DROP SEQUENCE  ROLES_ID_SEQ;
DROP SEQUENCE  DEPTS_ID_SEQ;

DROP TABLE  Employees;
DROP TABLE  Roles;
DROP TABLE  Departments;
